output_dir: outputs/hp-config3-deep
tokenizer_encoding: gpt2
model_config:
  n_embd: 48
  n_head: 3
  n_positions: 128
  n_layer: 4
device: auto
batch_size: 32
seq_len: 128
num_warmup_steps: 25
num_training_steps: 2500
grad_accumulation_steps: 1
min_lr: 1e-4
max_lr: 5e-4
