output_dir: outputs/hp-config5-balanced
tokenizer_encoding: gpt2
model_config:
  n_embd: 56
  n_head: 4
  n_positions: 128
  n_layer: 3
device: auto
batch_size: 32
seq_len: 128
num_warmup_steps: 40
num_training_steps: 4000
grad_accumulation_steps: 1
min_lr: 1e-4
max_lr: 5e-4
